language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
install:
  - pip install nose coverage
  - pip install -r requirements.txt
  - python setup.py develop
script: 
  - nosetests --with-coverage --cover-package=pmr2.wfctrl --with-doctest --doctest-options=+ELLIPSIS
after_success:
  - pip install coveralls
  - coveralls
branches:
  only:
    - master
